basePath: /api
definitions:
  model.AdminReq:
    properties:
      name:
        type: string
      password:
        type: string
    required:
    - name
    - password
    type: object
  model.AdminResp:
    properties:
      contact:
        type: string
      name:
        type: string
    type: object
  model.Book:
    properties:
      author:
        type: string
      category:
        type: string
      id:
        type: integer
      press:
        type: string
      price:
        type: number
      stock:
        type: integer
      title:
        type: string
      total:
        type: integer
      year:
        type: integer
    type: object
  model.BookReq:
    properties:
      author:
        type: string
      category:
        type: string
      press:
        type: string
      price:
        type: number
      title:
        type: string
      total:
        type: integer
      year:
        type: integer
    required:
    - author
    - category
    - press
    - price
    - title
    - total
    - year
    type: object
  model.CardReq:
    properties:
      department:
        type: string
      name:
        type: string
      type:
        type: string
    required:
    - department
    - name
    - type
    type: object
host: ralxyz.dev.zjuqsc.com
info:
  contact: {}
  description: This API will be used under staging environment.
  title: Book Management System API
  version: "0.2"
paths:
  /book:
    put:
      consumes:
      - application/json
      parameters:
      - description: Information of a book
        in: body
        name: book
        required: true
        schema:
          $ref: '#/definitions/model.BookReq'
      produces:
      - text/plain
      responses:
        "200":
          description: ""
      summary: Create a single book item
      tags:
      - Book
  /books:
    get:
      parameters:
      - in: query
        name: author
        type: string
      - in: query
        name: category
        type: string
      - in: query
        name: press
        type: string
      - in: query
        name: priceMax
        type: integer
      - in: query
        name: priceMin
        type: integer
      - in: query
        name: title
        type: string
      - in: query
        name: yearMax
        type: integer
      - in: query
        name: yearMin
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Book'
            type: array
        "400":
          description: Bad request
          schema:
            type: string
      summary: Retrieve multiple books under multiple conditions
      tags:
      - Book
    put:
      consumes:
      - text/csv
      parameters:
      - description: A csv file, with book information inside
        in: body
        name: file
        required: true
        schema:
          type: object
      produces:
      - text/plain
      responses:
        "200":
          description: ""
      summary: Create multiple book items by uploading a csv file
      tags:
      - Book
  /borrow:
    get:
      parameters:
      - description: Card ID
        in: query
        name: cardId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Book'
            type: array
        "400":
          description: Bad request
          schema:
            type: string
      summary: Get the books borrowed by a specific Bard
      tags:
      - Borrow
  /card:
    delete:
      parameters:
      - description: Card ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - text/plain
      responses:
        "200":
          description: ""
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: ""
      summary: Delete a library card
      tags:
      - Card
    put:
      parameters:
      - description: ' '
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.CardReq'
      produces:
      - application/json
      responses:
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: ""
      summary: Create a library card
      tags:
      - Card
  /login:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.AdminResp'
        "401":
          description: Not logged in
          schema:
            type: string
      summary: Check login status
      tags:
      - Login
    post:
      consumes:
      - application/json
      parameters:
      - description: Login information
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.AdminReq'
      produces:
      - text/plain
      responses:
        "200":
          description: ""
      summary: Admin login
      tags:
      - Login
swagger: "2.0"
